// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebPostgresqlDemo.Models;

#nullable disable

namespace WebPostgresqlDemo.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebPostgresqlDemo.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "smit@google.com",
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            Email = "silver@google.com",
                            Name = "Anna Silver"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mitchell@google.com",
                            Name = "John Mitchell"
                        },
                        new
                        {
                            Id = 4,
                            Email = "haynes@google.com",
                            Name = "Justin Haynes"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lopez@google.com",
                            Name = "Charles Lopez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
