CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

INSERT INTO "User" ("Id", "Email", "Name")
VALUES (1, 'smit@google.com', 'John Smith');
INSERT INTO "User" ("Id", "Email", "Name")
VALUES (2, 'silver@google.com', 'Anna Silver');
INSERT INTO "User" ("Id", "Email", "Name")
VALUES (3, 'mitchell@google.com', 'John Mitchell');
INSERT INTO "User" ("Id", "Email", "Name")
VALUES (4, 'haynes@google.com', 'Justin Haynes');
INSERT INTO "User" ("Id", "Email", "Name")
VALUES (5, 'lopez@google.com', 'Charles Lopez');

SELECT setval(
    pg_get_serial_sequence('"User"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "User") + 1,
        nextval(pg_get_serial_sequence('"User"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230824095732_Init', '7.0.10');

COMMIT;